### ISSUE TITLE
[Feature Request] Block shortened URLs 

### ISSUE THREAD

**Issue by davidjcralph** [NinoDiscord/Nino#304]
Shortened URLs are super dodgy. 

Once implemented, I can provide a list of URLs to block if you need me to.

**Comment by dondish** [comment]
Umm, maybe write a service that accesses the urls and checks for blacklisted sites?
This idea needs to be worked on for a little bit before full development.

**Comment by auguwu** [comment]
This would be easy to implement as an Automod/Service feature.

**Comment by auguwu** [comment]
Implemented in v1 of Nino
