### ISSUE TITLE
[Feature Request] Simplify commands, events and automod to make them more testable.

### ISSUE THREAD

**Issue by dondish** [NinoDiscord/Nino#327]
**Is your feature request related to a problem? Please describe.**
Commands should be the easiest part of the coding process, but due to the settings and translation API, the code is badly formatted and unreadable.

It's even worse than that, not having any formal way to code commands makes the code harder to test, which makes us only test manually. This may be good if the API is consistent, but as we can see from recent events, that it's not the case and caused many bugs.

**Describe the solution you'd like**
The solution consists of several steps:
* Test API - for testing commands and events, making it easier by abstracting the environment and making it easy to simulate events and users.
* Command API - for uniting all commands around one tested API. Making it much harder to have bugs in the command.

This solution will need some kind of draft, to not make them another inconsistent APIs like the Translation API. 

**Describe alternatives you've considered**
Another alternative solution is to make commands simpler to understand, without an API, but that will lose the uniformity of the testability of each command.

**Comment by dondish** [comment]
misclicked lol

**Comment by dondish** [comment]
I was thinking of commands returning interaction, a class that can include a callback function for additional input.
that way it will be much easier to test the commands knowing the will do something and then return interaction, without waiting on input in the process.

**Comment by dondish** [comment]
We are working on a new command framework called Commander, which will replace our current command handler, internationalization manager, and automod manager. 
It will be tested on its own and will be highly customizable and testable, making it easier for our development team and other's (it's open-source, feel free to use) to develop testable commands and events.

**Comment by dondish** [comment]
https://github.com/NinoDiscord/Commander

**Comment by titanabrian** [comment]
Hei @dondish can i help you to work on this as well?

**Comment by auguwu** [comment]
Implemented.
