### ISSUE TITLE
[Bug] Fix mute/unmute spam issue

### ISSUE THREAD

**Issue by auguwu** [NinoDiscord/Nino#417]
**Describe the bug**
Spams the "mod log" channel with a bunch of cases because of calculating bigints over numbers

![issue](https://i.augu.dev/cdb1.png)

**To Reproduce**
1. Mute a user for over a week
2. Wait that duration
3. Nino spams mod-log

**Expected behavior**
It shouldn't spam the mod-log channel

**Screenshots**
View above

**Discord (please complete the following information):**
Not applicable in this situation

**Additional context**
None at the moment

**Comment by dondish** [comment]
The timeout time can be found at:
* The settings command
* Tempban 
* Tempmute
All of them will need to be converted to bigint.

**Comment by auguwu** [comment]
Issue is fixed -- for future reference:

Do not use asynchronous operations in setTimeout with big timeouts, it'll cause to spam; the bigger the timeout
