### ISSUE TITLE
Custom Prefix

### ISSUE THREAD

**Issue by fnionn** [NinoDiscord/Nino#616]
**Is your feature request related to a problem? Please describe.**
Sometimes in servers, people like to customise the bot to suit the prefix that is easiest to them.

**Describe the solution you'd like**
A custom command system that uses a command to change prefix, e.g ```nino <prefix>```

**Comment by auguwu** [comment]
This has already existed for a while. Use `nino settings set prefix <prefix to use>` to set the prefix or use `nino settings reset prefix` to reset it.
