### ISSUE TITLE
[Feature Request] More than 15 punishments

### ISSUE THREAD

**Issue by boehs** [NinoDiscord/Nino#705]
**Is your feature request related to a problem? Please describe.**

> You can have up to 15 punishments (in total)!

From the docs (https://github.com/NinoDiscord/Nino/wiki/Managing-Guild-Settings)

**Describe the solution you'd like**

U N L I M I T E D    T I E R S

**Additional context**

I see no technical reason for this arbitrary limit

**Comment by auguwu** [comment]
I don't plan on adding tiers to punishments, the limit exists for a reason, which being, that no guilds shouldn't have colliding punishments / duplicates.

**Comment by boehs** [comment]
> I don't plan on adding tiers to punishments, the limit exists for a reason, which being, that no guilds shouldn't have colliding punishments / duplicates.

That is an arbitrary limit, consider this

* Mute, 5m
* Mute, 10m
* Mute, 30m
* Mute, 1h
* Mute, 6h
* Mute, 12h
* Mute, 1d
* Kick
* Ban, 1d
* Ban, 3d
* Ban, 5d
* Ban, 7d
* Ban, 14d
* Ban, 1m
* Ban, 3m
* Ban, forever

Although long, this is 16. Artificial limits remove power of choice from users and are annoying. A proper solution may be to notify users they might be making a mistake at 15 tiers.

> **Hey There! 🛑**
> You just hit 15 tiers. At this amount, conflicts between tiers often emerge. If you understand what you are doing, feel free to continue. Otherwise, consider viewing your tier list and ensuring everything looks right
