### ISSUE TITLE
[Feature Request] Command aliases 

### ISSUE THREAD

**Issue by boehs** [NinoDiscord/Nino#707]
To make it easier to come from other bots. This is a list of aliases I have thought of 

* ~~`prune`: `purge`~~
* `ban --soft`: `softban`
* `warn`: `point`
* `warnings`: `points`, `checkpoints` `checkwarnings`

**Comment by auguwu** [comment]
More command aliases are coming in the rewrite, please stop creating issues I already know.

**Comment by boehs** [comment]
> More command aliases are coming in the rewrite

How can I understand what is coming in the rewrite when it is not documented anywhere?

> please stop creating issues I already know

So, don't suggest features? That sounds counterintuitive?

**Comment by auguwu** [comment]
> How can I understand what is coming in the rewrite when it is not documented anywhere?

The rewrite is nowhere finished to be stable in production, so documentation doesn't exist, it'll exist once it's in production right now.

> So, don't suggest features? That sounds counterintuitive?

I'm not saying stop suggesting features, I'm saying stop creating issues that me or other developers know / are well known that need to be fixed.

> All the issues I have opened are new feature requests anyway

All the issues you have created (#708 & #704 are exceptions) are well known issues I already know and hold off or planned in the next version.

**Comment by boehs** [comment]
> All the issues you have created (#708 & #704 are exceptions) are well known issues I already know and hold off or planned in the next version.

Look, I don't want to fight about this, continuing development on a bot that archives the same thing is redundant and a waste of my time, but I am unsure of how you wish for me to know what is planned. The other two issues are #707 and #705. Just to ensure I have not missed anything, I reread all the issues.

I could not find one that mentioned the questions raised in #705 and #707, so it is unclear to me what features you guys have thought up internally and what are new suggestions :), I hope I am not missing something obvious. If so, do point me in the correct direction
