### ISSUE TITLE
Cant run it

### ISSUE THREAD

**Issue by Nuker90000** [NinoDiscord/Nino#911]
When i try to run it it says this:

**Comment by Nuker90000** [comment]
Replit: Updating package configuration

--> yarn add fs
yarn add v1.22.5
[1/5] Validating package.json...
error nino@1.4.2: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.6"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
exit status 1


Replit: Package operation failed.

**Comment by auguwu** [comment]
Nino was never meant to be ran from Repl.it or any free "hosting solutions." Please use the [public instance](https://discord.com/oauth2/authorize?client_id=531613242473054229&scope=bot+applications.commands) if you want the same experience from self-hosting or if you really want to, please buy a VPS to host it.
